name: Docs Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          access-token: e766a34ac877e5da2cdd8ad44052747a4ca23c28
          source-directory: docs
          build-command: yarn run docs
