name: Build Docs

on:
  push:
    branches: master

jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: |
          npm install
          npm run docs
